### ISSUE TITLE
Homebrew installation seems broken

### ISSUE THREAD

**Issue by gunnnnii** [DEEP-IMPACT-AG/skuld#10]
Installing skuld through homebrew seems to be broken, both me an florim run into this same issue:

```
brew tap DEEP-IMPACT-AG/hyperdrive
brew install skuld
Error: skuld: wrong number of arguments (given 1, expected 0)
```

Any idea what the problem could be? @thenonameguy

My system info
Apple M2 (MacBook Air)
macOS Ventura 13.0
Homebrew 4.0.6

Florim's system info
Apple M1 (MacBook Pro)
macOS Big Sur 11.5.2
Homebrew 4.0.6

**Comment by gilbertfrancois** [comment]
Homebrew support has been dropped in favour of docker.
